package ru.devinside.drm.fairplay.ksm.ckc;

import org.apache.commons.lang3.RandomUtils;

/**
 * A random 16-byte initialization vector, generated by the KSM, that has a unique value for each CKC message.
 * The vector is used to initialize the first block of the AES_CBC chain.
 */
public class CkcDataIv {
    public final static int CPC_DATA_IV_SIZE = 16;

    private final byte[] iv;

    public static CkcDataIv generate() {
        byte[] randomIv = RandomUtils.nextBytes(CPC_DATA_IV_SIZE);
        return new CkcDataIv(randomIv);
    }

    public CkcDataIv(byte[] iv) {
        this.iv = iv;
    }

    public byte[] getIv() {
        return iv;
    }
}
